### ISSUE TITLE
Stopped working on ubuntu 23.04

### ISSUE THREAD

**Issue by mayurts** [xen0l/aws-gate#1725]
Hi Team,

Greetings!

From this morning when i have upgraded ubuntu version from 22.04 to 23.04 aws-gate stopped working.

OS: ubuntu 23.04
Python: 3.11.2
aws-gate: 0.11.2

simple aws-gate command results into following error:
`Traceback (most recent call last):
  File "/home/mayur/.local/bin/aws-gate", line 3, in <module>
    import aws_gate.cli
  File "/home/mayur/.local/pipx/venvs/aws-gate/lib/python3.11/site-packages/aws_gate/cli.py", line 25, in <module>
    from aws_gate.exec import exec
  File "/home/mayur/.local/pipx/venvs/aws-gate/lib/python3.11/site-packages/aws_gate/exec.py", line 4, in <module>
    from aws_gate.decorators import (
  File "/home/mayur/.local/pipx/venvs/aws-gate/lib/python3.11/site-packages/aws_gate/decorators.py", line 7, in <module>
    from wrapt import decorator
  File "/home/mayur/.local/pipx/venvs/aws-gate/lib/python3.11/site-packages/wrapt/__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "/home/mayur/.local/pipx/venvs/aws-gate/lib/python3.11/site-packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/lib/python3.11/inspect.py)
`
Can you please help fixing the problem?

**Comment by dp-motive-numo** [comment]
Same issue here for me on Macbook, think possibly related to https://github.com/GrahamDumpleton/wrapt/issues/196 which is marked as resolved as of 1.14.0, however I'm unable to use aws-gate.

**Comment by jlongman** [comment]
duplicates #1598 - from what I see the fix just needs to be released

**Comment by xen0l** [comment]
Hey, I am working on releasing a new version, which should address this. Thanks for the patience and continued support of aws-gate!
